i18n: ES - translate file concepts/function-components/pre-defined-hooks.md
luisorbaiceta/yew pull request #9
Opened 2022-10-18 14:05 UTC by hereje

#### Description

 translate file `concepts/function-components/pre-defined-hooks.md` to spanish

#### Checklist

- [x] I have reviewed my own code

2022-10-19 07:46 UTC, luisorbaiceta commented
I'm on it. I'll try to review asap

2022-10-24 06:51 UTC, luisorbaiceta requested changes

2022-10-24 06:51 UTC, luisorbaiceta commented on website/i18n/es/docusaurus-plugin-content-docs/current/concepts/function-components/pre-defined-hooks.md
> +Este hook siempre lanzará una nueva renderización al recibir un nuevo estado. Ve [`use_state_eq`](#use_state_eq) si quieres que el componente sólo vuelva a renderizar cuando cambie el estado.
```suggestion
Este hook siempre lanzará una nueva renderización al recibir un nuevo estado. Utiliza [`use_state_eq`](#use_state_eq) si quieres que el componente sólo vuelva a renderizar cuando cambie el estado.
```

2022-10-24 06:51 UTC, luisorbaiceta commented on website/i18n/es/docusaurus-plugin-content-docs/current/concepts/function-components/pre-defined-hooks.md
> +actualización de renderización cuando el setter reciba un valor dónde `prev_state != next_state`.
```suggestion
actualización de renderización cuando el setter reciba un valor donde `prev_state != next_state`.
```

2022-10-24 06:51 UTC, luisorbaiceta commented on website/i18n/es/docusaurus-plugin-content-docs/current/concepts/function-components/pre-defined-hooks.md
> +El valor retenido en el manejo reflejará el valor al momento que el manejo
Qué significa "el manejo" en este contexto?

2022-10-24 06:51 UTC, luisorbaiceta commented on website/i18n/es/docusaurus-plugin-content-docs/current/concepts/function-components/pre-defined-hooks.md
> +Este retorna un objeto `UseStateHandle` el cual se `desreferencia` al valor actual
```suggestion
Este devuelve un objeto `UseStateHandle` el cual se `desreferencia` al valor actual
```
Esto lo marco pero no sé si es algo del idioma. Siempre he escuchado la palabra `devolver` en funciones. Lo dejo abierto a discusión

2022-10-24 14:15 UTC, hereje commented on website/i18n/es/docusaurus-plugin-content-docs/current/concepts/function-components/pre-defined-hooks.md
> +Este retorna un objeto `UseStateHandle` el cual se `desreferencia` al valor actual
De acuerdo. Hace más sentido.

2022-10-24 14:33 UTC, hereje commented on website/i18n/es/docusaurus-plugin-content-docs/current/concepts/function-components/pre-defined-hooks.md
> +El valor retenido en el manejo reflejará el valor al momento que el manejo
El texto original es

"The value held in the handle will reflect the value at the time the
handle is returned by the `use_state`"

Hace referencia a handle. No estoy seguro si la interpretación que hice fue la correcta.

2024-02-20 17:01 UTC, merged